repos:
    - repo: https://github.com/python/black
      rev: stable
      hooks:
      - id: black
        stages: [commit]
        language_version: python3.7
        args: [--check]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.7
      hooks:
      - id: flake8
        stages: [commit]
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v1.0.0
      hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
    - repo: local
      hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint.__main__
        language: system
        types: [python]
        stages: [commit]
        args: [-E]
