repos:
    - repo: https://github.com/python/black
      rev: stable
      hooks:
      - id: black
        stages: [commit]
        language_version: python3.7
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.7
      hooks:
      - id: flake8
        stages: [commit]
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v1.0.0
      hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v2.3.1
      hooks:
      - id: pylint
        args: [-E]
        stages: [commit]
