from .vanilla import vanilla
from .trpo import trpo
from .a2c import a2c
from .ppo import ppo
from .acktr import acktr
from .a2c_kfac import a2c_kfac
from .ddpg import ddpg
from .td3 import td3
from .sac import sac
